### PR TITLE
Update Github polling

### PR DESCRIPTION
**Pull request by okotek**

### CODE REVIEW

**Review by mrT23 — APPROVED** [review]

**Comment by okotek** [comment]
/ask is this PR ready to merge?

**Comment by okotek** [comment]
/ask write me a poem about this PR

**Comment by okotek** [comment]
@codium-argocd /ask write me a poem about this PR

**Comment by okotek** [comment]
@CodiumAI-Agent /ask write me a poem about this PR

**Comment by okotek** [comment]
@CodiumAI-Agent /ask write me a poem about this PR

**Pull request merged**
