### PR TITLE
print test

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
other

___

### **Description**
- Added a print statement "testing ..." to `setup.py` for testing purposes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Miscellaneous</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>setup.py</strong><dd><code>Add print statement for testing in setup.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

setup.py

- Added a print statement for testing purposes.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1385/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by lagnx** [comment]
Preparing review...

**Comment by jong47** [comment]
Preparing review...

**Comment by jong47** [comment]
**[Persistent review](https://github.com/qodo-ai/pr-agent/pull/1385#issuecomment-2525450880)** updated to latest commit https://github.com/qodo-ai/pr-agent/commit/401dc29deea775ce08cbac247206ca450099345f

**Comment by jong47** [comment]
**[Persistent review](https://github.com/qodo-ai/pr-agent/pull/1385#issuecomment-2525450880)** updated to latest commit https://github.com/qodo-ai/pr-agent/commit/401dc29deea775ce08cbac247206ca450099345f

**Comment by jong47** [comment]
**[Persistent review](https://github.com/qodo-ai/pr-agent/pull/1385#issuecomment-2525450880)** updated to latest commit https://github.com/qodo-ai/pr-agent/commit/401dc29deea775ce08cbac247206ca450099345f

**Pull request closed without merging**
