### PR TITLE
Support for Repo-Specific Configuration File

### PR DESCRIPTION
**Pull request by okotek**
## PR Type:
Enhancement

___
## PR Description:
This PR introduces the ability to use a repository-specific configuration file (.pr_agent.yaml) for the PR Agent. This allows different repositories to have different settings according to their specific needs. The changes are implemented for both GitHub and GitLab providers.

___
## PR Main Files Walkthrough:
- `pr_agent/git_providers/github_provider.py`: Added logic to check if the use of a repo-specific settings file is enabled. If so, it attempts to fetch the .pr_agent.yaml file from the repository, creates a temporary file with its contents, and loads the settings from it.
- `pr_agent/git_providers/gitlab_provider.py`: Similar changes as in the GitHub provider, but adapted for GitLab's API.
- `pr_agent/settings/configuration.toml`: Added a new configuration option 'use_repo_settings_file' to enable or disable the use of a repo-specific settings file.

### CODE REVIEW

**Comment by patryk-kowalski-ds** [comment]
Repo-specific configuration is already implemented for LocalGitProvider using pyproject.toml file. Might be good to use pyproject.toml here too, for consistency

**Comment by okotek** [comment]
> Repo-specific configuration is already implemented for LocalGitProvider using pyproject.toml file. Might be good to use pyproject.toml here too, for consistency

I don't think it's a good idea to add a "pyproject.toml" to arbitrary projects, that are (1) not necessarily in Python (2) Might already have pyproject.toml file

**Comment by patryk-kowalski-ds** [comment]
> > Repo-specific configuration is already implemented for LocalGitProvider using pyproject.toml file. Might be good to use pyproject.toml here too, for consistency
> 
> I don't think it's a good idea to add a "pyproject.toml" to arbitrary projects, that are (1) not necessarily in Python (2) Might already have pyproject.toml file

Right, I haven't considered non-python projects. In this case LocalGitProvider should support pr_agent.yaml. I'll work on that.

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
