### PR TITLE
delete "Preparing review..." comment

### PR DESCRIPTION
**Pull request by mrT23**
Remove the temporary "Preparing review..." comment once we done generating the actual output

### CODE REVIEW

**Review by okotek — APPROVED** [review]

**Comment by cometbaydo** [comment]
Failed to generate setup guide for PR. Error: 'File' object has no attribute 'lower'

**Comment by MatheusFelipeMarinho** [comment]
Preparing PR description...

**Comment by MatheusFelipeMarinho** [comment]
Preparing PR description...

**Comment by MatheusFelipeMarinho** [comment]
### **Ask**❓
Explique o que este PR faz de forma simples

### **Answer:**
Este PR faz uma modificação simples, mas importante, no comportamento do sistema de revisão de Pull Requests. Aqui está uma explicação simples do que o PR faz:

1. Remove o comentário temporário "Preparing review..." ou "Preparing answer..." após a geração da revisão ou resposta real.

2. Adiciona uma nova funcionalidade para marcar comentários como temporários quando são publicados.

3. Implementa um novo método `remove_initial_comment()` que remove os comentários marcados como temporários.

4. Atualiza o processo de publicação de comentários para usar essa nova funcionalidade, garantindo que o comentário inicial temporário seja removido após a conclusão da revisão ou resposta.

5. Adiciona tratamento de erros para lidar com possíveis falhas na remoção do comentário inicial.

6. Melhora a mensagem de erro quando o token do GitHub não está configurado corretamente, fornecendo um link para a documentação.

7. Faz algumas pequenas alterações no README.md, removendo alguns itens de "TODO" e simplificando a estrutura.

Em resumo, este PR melhora a experiência do usuário ao eliminar comentários temporários desnecessários e fornece uma melhor orientação em caso de erros de configuração.

**Comment by pratik-abhang-comprinno** [comment]
## 🤖 PR Review

### Summary of Changes

This Pull Request aims to delete the "Preparing review..." and "Preparing answer..." comments after the actual review or answer has been posted. The changes include:

1. **README.md**: Removed a section that was marked as TBD.
2. **github_provider.py**:
   - Added a method `remove_initial_comment` to delete temporary comments.
   - Modified the `publish_comment` method to accept an `is_temporary` flag and store comments in a list.
3. **pr_questions.py** and **pr_reviewer.py**:
   - Updated the `answer` and `review` methods to mark initial comments as temporary and remove them after posting the actual content.

### Potential Issues or Bugs

1. **Comment Tracking**:
   - The current implementation stores comments in a list attached to the PR object. This might not persist across different runs of the application, leading to potential issues in comment removal.
   
2. **Error Handling**:
   - In `remove_initial_comment`, the exception is logged but not re-raised. Depending on the application’s requirements, you might want to handle this more gracefully or ensure the error propagates.

3. **Temporary Flag Usage**:
   - Ensure that the `is_temporary` flag is consistently used across all places where comments are published to avoid leaving orphaned temporary comments.

### Security Concerns

1. **Error Logging**:
   - The error message in `remove_initial_comment` logs the exception, which could potentially expose sensitive information. Consider sanitizing the logged output to avoid leaking any confidential data.

### Code Quality Suggestions

1. **Type Hints**:
   - Add type hints for function parameters and return types to improve code readability and maintainability.
   
2. **Docstrings**:
   - Add docstrings to methods to explain their purpose, parameters, and return values. This will help other developers understand the code more quickly.
   
3. **Configuration Handling**:
   - Ensure that configuration settings like `settings.config.publish_review` are properly validated and documented.

4. **Testing**:
   - Add unit tests to cover the new `remove_initial_comment` method and the changes in `publish_comment` to ensure they work as expected.

### Estimated Review Effort

- **Time Required**: Approximately 15-20 minutes for a thorough review, including testing the changes in a staging environment if possible.

**Comment by kumarharshgaur** [comment]
Preparing review...

**Comment by innotech-it** [comment]
Preparing review...

**Comment by Wuvies** [comment]
Preparing review...

**Comment by aravinthananth-del** [comment]
**[Persistent review](https://github.com/The-PR-Agent/pr-agent/pull/1#issuecomment-4067732785)** updated to latest commit https://github.com/The-PR-Agent/pr-agent/commit/f1004273ecbcbba45bc240673acd89b518c28ab3

**Comment by Sheeba1910** [comment]
Preparing review...

**Comment by Sheeba1910** [comment]
Preparing review...

**Comment by Sheeba1910** [comment]
Preparing review...

**Comment by Sheeba1910** [comment]
**[Persistent review](https://github.com/The-PR-Agent/pr-agent/pull/1#issuecomment-4067732785)** updated to latest commit https://github.com/The-PR-Agent/pr-agent/commit/f1004273ecbcbba45bc240673acd89b518c28ab3

**Comment by Peanow** [comment]
Preparing review...

**Comment by Peanow** [comment]
Preparing review...

**Comment by Peanow** [comment]
**[Persistent review](https://github.com/The-PR-Agent/pr-agent/pull/1#issuecomment-4067732785)** updated to latest commit https://github.com/The-PR-Agent/pr-agent/commit/f1004273ecbcbba45bc240673acd89b518c28ab3

**Comment by linming413589901** [comment]
Preparing review...

**Comment by linming413589901** [comment]
Preparing review...

**Comment by linming413589901** [comment]
Preparing review...

**Comment by linming413589901** [comment]
Preparing review...

**Comment by linming413589901** [comment]
Preparing review...

**Comment by linming413589901** [comment]
**[Persistent review](https://github.com/The-PR-Agent/pr-agent/pull/1#issuecomment-4067732785)** updated to latest commit https://github.com/The-PR-Agent/pr-agent/commit/f1004273ecbcbba45bc240673acd89b518c28ab3

**Comment by joohyun97** [comment]
**[Persistent review](https://github.com/The-PR-Agent/pr-agent/pull/1#issuecomment-4067732785)** updated to latest commit https://github.com/The-PR-Agent/pr-agent/commit/f1004273ecbcbba45bc240673acd89b518c28ab3

**Comment by Mahesh0002** [comment]
## PR Reviewer Guide 🔍



Here are some key observations to aid the review process:

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

<details><summary><a href='https://github.com/The-PR-Agent/pr-agent/pull/1/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R34-R57'><strong>Possible Issue</strong></a>

The `remove_initial_comment` method in the `github_provider.py` file is not called when the `publish_comment` method is used with `is_temporary=True`. This could lead to a situation where the initial comment is not removed, even if it is intended to be temporary.
</summary>

```python
def get_diff_files(self) -> list[FilePatchInfo]:
    files = self.pr.get_files()
    diff_files = []
    for file in files:
        original_file_content_str = self._get_pr_file_content(file, self.pr.base.sha)
        new_file_content_str = self._get_pr_file_content(file, self.pr.head.sha)
        diff_files.append(FilePatchInfo(original_file_content_str, new_file_content_str, file.patch, file.filename))
    return diff_files

def publish_comment(self, pr_comment: str, is_temporary: bool = False):
    response = self.pr.create_issue_comment(pr_comment)
    response.is_temporary = is_temporary
    if not hasattr(self.pr, 'comments_list'):
        self.pr.comments_list = []
    self.pr.comments_list.append(response)

def remove_initial_comment(self):
    try:
        for comment in self.pr.comments_list:
            if comment.is_temporary:
                comment.delete()
    except Exception as e:
        logging.exception(f"Failed to remove initial comment, error: {e}")

```

</details>

<details><summary><a href='https://github.com/The-PR-Agent/pr-agent/pull/1/files#diff-71970fafa37a18dfb27eb7b47754bfa7841e14686b181445298f914e03fc31aaR30-R40'><strong>Possible Issue</strong></a>

The `answer` method in the `pr_questions.py` file does not check if the `settings.config.publish_review` flag is set before calling the `publish_comment` method. This could lead to a situation where the comment is published even if it is not intended to be published.
</summary>

```python
                                      self.vars,
                                      settings.pr_questions_prompt.system,
                                      settings.pr_questions_prompt.user)
    self.patches_diff = None
    self.prediction = None

async def answer(self):
    logging.info('Answering a PR question...')
    if settings.config.publish_review:
        self.git_provider.publish_comment("Preparing answer...", is_temporary=True)
    logging.info('Getting PR diff...')
```

</details>

</td></tr>
</table>

**Pull request merged**
