### PR TITLE
Retry on Rate Limit Error

### PR DESCRIPTION
**Pull request by okotek**
PR Type:
**Bug fix**

___
PR Description:
**This PR increases the number of retries for OpenAI API calls and adds handling for rate limit errors. It also includes logging for unknown errors during OpenAI inference.**

___
PR Main Files Walkthrough:
- `pr_agent/algo/ai_handler.py`: The number of retries for OpenAI API calls has been increased from 2 to 5. The `retry` decorator on the `chat_completion` method now includes `RateLimitError` in its list of exceptions to retry on. Additional exception handling has been added for `RateLimitError` and unknown exceptions, both of which log the error and re-raise it.

### CODE REVIEW

**Review by ezzcodeezzlife — APPROVED** [review]

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
/answer
1. yes
2. in the future we will add a fallback model
3. no specific scenario, general protection

**Comment by almog-lv** [comment]
/answer

1. yes
2. in the future we will add a fallback model
3. no specific scenario, general protection

**Pull request merged**
