### PR TITLE
Add PR help message functionality and update dependencies

### PR DESCRIPTION
**Pull request by mrT23**
### **User description**
- Implement PRHelpMessage class to provide AI-powered assistance for pull requests.
- Add methods for similarity search using local, S3, and Pinecone databases.
- Update `requirements.txt` to include new dependencies for langchain and chromadb.
- Modify `configuration.toml` to include `force_local_db` setting for PR help.
- Update `aiohttp` and `openai` package versions.

___

### **PR Type**
Enhancement

___

### **Description**
- Implemented AI-powered PR help functionality in the PRHelpMessage class
- Added methods for similarity search using local, S3, and Pinecone databases
- Improved error handling and logging throughout the PR help process
- Updated PR help message generation to support different Git providers
- Added 'force_local_db' configuration option in configuration.toml
- Updated aiohttp and openai package versions in requirements.txt
- Added new dependencies for langchain, chromadb, and related packages to support AI-powered functionality

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_help_message.py</strong><dd><code>Implement AI-powered PR help functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_help_message.py

<li>Implemented PRHelpMessage class with AI-powered assistance for pull <br>requests<br> <li> Added methods for similarity search using local, S3, and Pinecone <br>databases<br> <li> Improved error handling and logging<br> <li> Updated PR help message generation for different Git providers<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1241/files#diff-6f30977025b20a27640fc33cfe2db79160753bd30c7879f60f2b5894d86f78de">+340/-96</a></td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add force_local_db configuration option</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

- Added 'force_local_db' option to pr_help section

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1241/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update dependencies and add new packages</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

<li>Updated aiohttp and openai package versions<br> <li> Added new dependencies for langchain, chromadb, and related packages<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1241/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
/help "how to change the code suggestion to be commitable ?"

**Comment by mrT23** [comment]
/help "how to change the code suggestion to be commitable ?"

**Comment by Zrmikstri** [comment]
/help "how to use pr-agent with self hosted llm"

**Comment by Zrmikstri** [comment]
can i use pr-agent with llama.cpp

**Review by hussam789 — APPROVED** [review]

**Comment by sparsh-b20** [comment]
/help what are the language it supports

**Comment by sparsh-b20** [comment]
/help I am using golang in my projects , is the review and other functionalities available for that
also , is it require my own open ai key

**Comment by sparsh-b20** [comment]
/help I am using Golang in my projects , will it qodo.ai will help me 
also , is it require my open ai key

**Comment by jaibhasin** [comment]
/help does it work with openrouter ?

**Comment by jaibhasin** [comment]
/ask does it have different subagents to review each aspect or the repo or not ?

**Pull request merged**
