### PR TITLE
Adding GitHub Actions Support and PR Description Feature

### PR DESCRIPTION
**Pull request by okotek**
Type of PR:
**Enhancement**

___
PR Description:
**This PR introduces two major enhancements. Firstly, it adds support for GitHub Actions, allowing the PR Agent to be used as a GitHub Action. Secondly, it introduces a new feature that generates a description for a given PR. The PR also includes necessary updates to the documentation and tests to reflect these changes.**

___
PR Main Files Walkthrough:
-`pr_agent/cli.py`: Added a new command-line argument for PR description.
-`pr_agent/config_loader.py`: Added a new settings file for PR description prompts.
-`pr_agent/git_providers/git_provider.py` and `pr_agent/git_providers/github_provider.py`: Added a new abstract method and its implementation for publishing PR descriptions.
-`pr_agent/servers/github_action_runner.py`: Added a new script to run the PR Agent as a GitHub Action.
-`pr_agent/tools/pr_description.py`: Added a new tool for generating PR descriptions.
-`tests/unit/test_convert_to_markdown.py` and `tests/unit/test_fix_output.py`: Updated tests to reflect the removal of 'Description and title' from the PR analysis.
-`.github/workflows/review.yaml`: Added a new GitHub Actions workflow for running the PR Agent.
-`Dockerfile.github_action`: Added a new Dockerfile for running the PR Agent as a GitHub Action.
-`README.md`: Updated the documentation to reflect the new changes.
-`pr_agent/settings/pr_description_prompts.toml`: Added a new settings file for PR description prompts.

### CODE REVIEW

**Comment by okotek** [comment]
review

**Comment by okotek** [comment]
review

**Comment by georgeseifada** [comment]
Great feature!

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
